joy_node:    #此文件主要作为joy_teleop.py的输入
  deadzone: 0.01
  autorepeat_rate: 20
  coalesce_interval: 0.01

teleop:
  # Default mode - Stop for safety
  default:
    type: topic           #需要发布的主题，类型和主题名字分别由message_type和topic_name定义
    is_default: true
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    message_value:        #如定义message_valiue,则用target=value作为主题的内容发布
      -
        target: drive.speed
        value: 0.0
      -
        target: drive.steering_angle
        value: 0.0

  # Enable Human control by holding Left Bumper
  human_control:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: []  #需要该按键按下才发布指定的消息主题
    axis_mappings:        #如定义axis_mappings,则target=axis*scale+offset
      -
        axis: 2           #teleop (FB) axis:0; G29 accelarator pedal is axis:2
        target: drive.speed
        scale:  0.0                 # joystick will command plus or minus 2 meters / second
        offset: 0.0
      -
        axis: 0           #teleop (LR) axis:2; G29 Streer is axis:0
        target: drive.steering_angle
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0

  human_control_D:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: [12]  
    axis_mappings:        #如定义axis_mappings,则target=axis*scale+offset
      -
        axis: 2           #teleop (FB) axis:0; G29 accelarator pedal is axis:2
        target: drive.speed
        scale:  0.5                   # joystick will command plus or minus 2 meters / second
        offset: 0.5
      -
        axis: 0           #teleop (LR) axis:2; G29 Streer is axis:0
        target: drive.steering_angle
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0

  human_control_R:
    type: topic
    message_type: ackermann_msgs/AckermannDriveStamped
    topic_name: low_level/ackermann_cmd_mux/input/teleop
    deadman_buttons: [17]  
    axis_mappings:        #如定义axis_mappings,则target=axis*scale+offset
      -
        axis: 2           #teleop (FB) axis:0; G29 accelarator pedal is axis:2
        target: drive.speed
        scale:  -0.5                   # joystick will command plus or minus 2 meters / second
        offset: -0.5
      -
        axis: 0           #teleop (LR) axis:2; G29 Streer is axis:0
        target: drive.steering_angle
        scale: 0.34                  # joystick will command plus or minus ~20 degrees steering angle
        offset: 0.0

  # Enable autonomous control by pressing right bumper
  # This switch causes the joy_teleop to stop sending messages to input/teleop
  # And send messages to /dev/null (an unused ROS topic)
  autonomous_control:
    type: topic
    message_type: std_msgs/Int8
    topic_name: /dev/null
    deadman_buttons: [5]
    message_value:
        target: data
        value: 0
